apiVersion: apps/v1
kind: Deployment
metadata:
  name: acc-3211-controller-manager
  namespace: kueue-system
  labels:
    control-plane: acc-3211-controller-manager
    app.kubernetes.io/name: acc-3211
spec:
  selector:
    matchLabels:
      control-plane: acc-3211-controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: acc-3211-controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /manager
        args:
          - --leader-elect
          - --health-probe-bind-address=:8081
        image: $YOUR_IMAGE_HERE
        name: manager
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: acc-3211-manager
      terminationGracePeriodSeconds: 10
